# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9f11e0f69bd91baaf091836138363a4971a7d18afe1011c306ac845c7d911542a96a2eed7e2623b3be15b1a8a365254f1db49d44fcbefa81c7155cebfbc7c14

test:
  secret_key_base: 71686777fec81da61b6afebdfe6d422f7429cef770f5ca4808ae0392ce3f250673e037681d352113163787415b157f575b816078bb09c3244fba597a018677b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
